export enum Locale {
  ZH_TW = 'ZH_TW',
}

export enum LocaleQuery {
  ZH_TW = 'hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
}

export enum Category {
  BUSINESS = 'CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  ENTERTAINMENT = 'CAAqKggKIiRDQkFTRlFvSUwyMHZNREpxYW5RU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  SPOTS = 'CAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  TECHNOLOGY = 'CAAqLAgKIiZDQkFTRmdvSkwyMHZNR1ptZHpWbUVnVjZhQzFVVnhvQ1ZGY29BQVAB',
  FINANCE = 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNREpmTjNRU0JYcG9MVlJYS0FBUAE',
  POLITICS = 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNRFZ4ZERBU0JYcG9MVlJYS0FBUAE',
  HEALTH = 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNR3QwTlRFU0JYcG9MVlJYS0FBUAE',
  PET = 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNRFk0YUhrU0JYcG9MVlJYS0FBUAE',
  GLOBAL = 'CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx1YlY4U0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
}
