services:
  nginx:
    build: ./docker/nginx/
    image: ${DOCKER_PREFIX}-nginx
    container_name: ${DOCKER_PREFIX}-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./frontend/dist:/usr/share/nginx/html
    environment:
      - TZ=${TZ}
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - public-network
      - internal-network
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    image: ${DOCKER_PREFIX}-frontend
    container_name: ${DOCKER_PREFIX}-frontend
    restart: always
    env_file:
      - .env
    networks:
      - internal-network
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: ${DOCKER_PREFIX}-backend
    container_name: ${DOCKER_PREFIX}-backend
    restart: always
    env_file:
      - .env
    environment:
      - ENABLED_SCHEDULE=false
    networks:
      - internal-network
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  cronjob:
    build:
      context: ./
      dockerfile: ./docker/cronjob/Dockerfile
    image: ${DOCKER_PREFIX}-cronjob
    container_name: ${DOCKER_PREFIX}-cronjob
    restart: always
    env_file:
      - .env
    environment:
      - ENABLED_SCHEDULE=true
    networks:
      - internal-network
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  migration:
    build:
      context: ./
      dockerfile: ./docker/migration/Dockerfile
    image: ${DOCKER_PREFIX}-migration
    container_name: ${DOCKER_PREFIX}-migration
    restart: on-failure
    env_file:
      - .env
    command: /bin/sh -c "npm run migration:run && tail -f /dev/null"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - internal-network
  postgres:
    image: postgres:latest
    container_name: ${DOCKER_PREFIX}-postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    networks:
      - internal-network
  redis:
    image: redis:latest
    container_name: ${DOCKER_PREFIX}-redis
    restart: always
    volumes:
      - redis-data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/log:/usr/local/redis/logs
    environment:
      - TZ=${TZ}
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - internal-network
volumes:
  postgres-data:
  redis-data:
networks:
  public-network:
  internal-network:
