services:
  nginx:
    build: ./docker/nginx/
    container_name: ${DOCKER_PREFIX}-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    environment:
      - TZ=${TZ}
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - public-net
    depends_on:
      - backend
    links:
      - backend
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: ${DOCKER_PREFIX}-backend
    restart: always
    env_file:
      - .env
    networks:
      - public-net
      - internal-net
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  migration:
    build:
      context: ./
      dockerfile: ./docker/migration/Dockerfile
    container_name: ${DOCKER_PREFIX}-migration
    restart: on-failure
    env_file:
      - .env
    command: /bin/sh -c "npm run migration:run && tail -f /dev/null"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - internal-net
  postgres:
    image: postgres:latest
    container_name: ${DOCKER_PREFIX}-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    networks:
      - public-net
      - internal-net
  redis:
    image: redis:latest
    container_name: ${DOCKER_PREFIX}-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/log:/usr/local/redis/logs
    environment:
      - TZ=${TZ}
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - public-net
      - internal-net
volumes:
  postgres-data:
  redis-data:
networks:
  public-net:
  internal-net:
