export const MAX_BROWSER_INSTANCES = 2;

export const MAX_USAGE_PER_BROWSER = 100;

export const BROWSER_EXPIRED_MILLISECONDS = 60 * 1000;

export const CLOSE_BROWSER_RETRY_COUNT = 10;

export const CLOSE_PAGE_RETRY_COUNT = 10;
