import { Category } from './enum.js';

export const NEWS_TABLE = 'news';

export const LOCALE_ENUM_NAME = `${NEWS_TABLE}_locale_enum`;

export const CATEGORY_ENUM_NAME = `${NEWS_TABLE}_category_enum`;

export const CATEGORY_MAPPING = {
  [Category.BUSINESS]:
    'CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  [Category.ENTERTAINMENT]:
    'CAAqKggKIiRDQkFTRlFvSUwyMHZNREpxYW5RU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  [Category.SPOTS]:
    'CAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
  [Category.TECHNOLOGY]:
    'CAAqLAgKIiZDQkFTRmdvSkwyMHZNR1ptZHpWbUVnVjZhQzFVVnhvQ1ZGY29BQVAB',
  [Category.FINANCE]: 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNREpmTjNRU0JYcG9MVlJYS0FBUAE',
  [Category.POLITICS]:
    'CAAqJQgKIh9DQkFTRVFvSUwyMHZNRFZ4ZERBU0JYcG9MVlJYS0FBUAE',
  [Category.HEALTH]: 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNR3QwTlRFU0JYcG9MVlJYS0FBUAE',
  [Category.PET]: 'CAAqJQgKIh9DQkFTRVFvSUwyMHZNRFk0YUhrU0JYcG9MVlJYS0FBUAE',
  [Category.GLOBAL]:
    'CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx1YlY4U0JYcG9MVlJYR2dKVVZ5Z0FQAQ',
};
